### ISSUE TITLE
Afvalinfo status is unavailable

### ISSUE THREAD

**Issue by beestarbush** [heyajohnny/afvalinfo#278]
Since a week or two it is not possible to retrieve the afvalstatus in city Apeldoorn. This is from company Circulus Berkel. Could you have a look into this? Thank you!

**Comment by heyajohnny** [comment]
Apeldoorn 7314HA 31 works without a problem

**Comment by heyajohnny** [comment]
@VelocityMaximus Altena switched to afvalstoffendienstkalender. I've just pushed an update.

**Comment by zzammerr** [comment]
Brummen, also Circulus Berkel, does not show anything, perhaps same change?

**Comment by heyajohnny** [comment]
@zzammerr Brummen works like a charm
![image](https://user-images.githubusercontent.com/20553716/159995873-813c6c11-2b5d-492a-9edc-f0eb6f6b19b6.png)

**Comment by JJ-Duf** [comment]
@heyajohnny For me it is still not possible to retrieve afvalstatus for region Best. Could you have a look at it as well? Thanks a lot!

**Comment by steef84** [comment]
westland werkt ook (weer) niet bij mij

**Comment by heyajohnny** [comment]
@JJ-Duf Best is also functioning just fine:
![image](https://user-images.githubusercontent.com/20553716/160294213-2ae71c08-fb8e-468d-875f-6b438ef190d0.png)

**Comment by heyajohnny** [comment]
@steef84 En ook Westland werkt prima:
![image](https://user-images.githubusercontent.com/20553716/160294283-551ef4a8-aaea-4837-81dd-80c317f4b930.png)

**Comment by SynoUser-NL** [comment]
Hi,

Heerlen (64xx YZ) RD4 doesn't work for me since some time.
Would you be able to fix this?

Thank you!

**Comment by robinwillems** [comment]
Had this same problem a couple of weeks ago... it seemed there were new entities that i needed to select.
Please check the integration if there are new entities and remove the old ones.

**Comment by steef84** [comment]
Yes, the answer above is my fix also

**Comment by JJ-Duf** [comment]
Thanks! That indeed solved it.

**Comment by SynoUser-NL** [comment]
Ahh.. That's an easy fix.. Thanks!
